cpp : 
   codes :
      properties : 
          E0001 : 用户凭证过期，请重新登录
          E0002 : 后台错误，请联系管理员
          E0003 : 验证码错误/过期
          E0004 : 短信验证码错误
          E0005 : 短信验证码过期
          E0006 : 用户账号已存在！
          E0007 : 短信验证码获取次数过多
          ES001 : 单点登陆验证信息过期 
          DL001 : 重定向登陆
          DL002 : 无效用户
          DL003 : 用户账号未同步，请联系管理员!
          DL004 : 用户账号已禁用,请联系系统管理员!
          DL005 : 退出登陆,重定向
